kind: pipeline
name: Bearer Python - Publish Package

steps:
  - name: Install, Build & Push
    image: python:3.7.2-slim
    commands:
      - python -m pip install twine
      - python -m pip install --user --upgrade setuptools wheel
      - python setup.py sdist bdist_wheel
      - echo "[pypi]\nusername = __token__\npassword = $TWINE_TOKEN" > ~/.pypirc
      - python -m twine upload dist/*

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-v*

---
kind: pipeline
name: Bearer Python - Publish TEST Package

steps:
  - name: Install
    image: python:3.7.2-slim
    commands:
      - python -m pip install --user tox
      - python -m pip install twine
      - python -m pip install --user --upgrade setuptools wheel
  - name: Test
    image: python:3.7.2-slim
    commands:
      - tox
  - name: Build
    image: python:3.7.2-slim
    commands:
      - python setup.py sdist bdist_wheel
  - name: Push
    image: python:3.7.2-slim
    commands:
      - echo "[pypi]\nusername = __token__\npassword = $TWINE_TEST_TOKEN" > ~/.pypirc
      - python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*

trigger:
  event:
    - tag
  ref:
    - refs/tags/release-test-v*

---
kind: pipeline
name: Bearer Python - Build and Test

clone:
  depth: 50

steps:
  - name: install dependencies
    image: python:3.7.2-slim
    commands:
      - python -m venv venv
      - venv/bin/pip install tox
  - name: test
    image: python:3.7.2-slim
    commands:
      - venv/bin/python -m tox

trigger:
  event:
    - pull_request
    - push
