on: push
name: Test
jobs:
  build:
    name: 'Test: Setup'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: 'Test: Setup'
      uses: docker://python:3.7.2-slim
      with:
        entrypoint: pip
        args: install --user tox
    - name: 'Test: Run'
      uses: docker://python:3.7.2-slim
      with:
        entrypoint: python
        args: -m tox
